k8s_masters:
  hosts:
    # Control nodes
    master-01:
      ansible_host: 158.160.117.57
      ansible_user: ubuntu
    # master-02:
    #   ansible_host: 62.84.116.50
    #   ansible_user: ubuntu
    # master-03:
    #   ansible_host: 51.250.88.162
    #   ansible_user: ubuntu

# nlb:
#   hosts:
#     # Control nodes
#     nlb:
#       ansible_host: 51.250.14.113
#       ansible_user: ubuntu

k8s_workers:
  hosts:
    # Worker nodes
    node-01:
      ansible_host: 158.160.126.84
      ansible_user: ubuntu
    # node-02:
    #   ansible_host: 84.252.128.21
    #   ansible_user: ubuntu
    # node-03:
    #   ansible_host: 158.160.119.154
    #   ansible_user: ubuntu
    # node-04:
    #   ansible_host: 51.250.14.150
    #   ansible_user: ubuntu
k8s_cluster:
  children:
    k8s_masters:
    k8s_workers:
